// src/utils/mentorshipConstants.ts

export interface LabelValue {
  label: string;
  value: string;
}

export interface AreaGroup {
  title: string;
  areas: LabelValue[];
}

interface Country {
  code: string;
  name: string;
}

export const PROFICIENCY_LEVELS: LabelValue[] = [
  { label: 'Beginner', value: 'BEGINNER' },
  { label: 'Intermediate', value: 'INTERMEDIATE' },
  { label: 'Advanced', value: 'ADVANCED' },
  { label: 'Expert', value: 'EXPERT' },
];

export const MENTORSHIP_TYPES: LabelValue[] = [
  { label: 'Long-Term', value: 'LONG_TERM' },
  { label: 'Ad-Hoc', value: 'AD_HOC' },
];

export const ALL_MENTORSHIP_TYPES = 'All';

export const FILTER_MENTORSHIP_TYPES_OPTIONS = [
  { label: 'All', value: ALL_MENTORSHIP_TYPES },
  { label: 'Long-term', value: 'Long-Term' },
  { label: 'Ad-hoc', value: 'Ad-Hoc' },
] as const;

export const MENTORSHIP_FOCUS_AREAS: LabelValue[] = [
  { label: 'Switch career to IT', value: 'SWITCH_CAREER_TO_IT' },
  { label: 'Grow from beginner to mid-level', value: 'GROW_BEGINNER_TO_MID' },
  { label: 'Grow from mid-level to senior-level', value: 'GROW_MID_TO_SENIOR' },
  { label: 'Grow beyond senior level', value: 'GROW_BEYOND_SENIOR' },
  {
    label: 'Switch from IC to management position',
    value: 'SWITCH_TO_MANAGEMENT',
  },
  { label: 'Change specialisation within IT', value: 'CHANGE_SPECIALISATION' },
];

export const TECHNICAL_AREA_GROUPS: AreaGroup[] = [
  {
    title: 'Software Development',
    areas: [
      { label: 'Backend', value: 'BACKEND' },
      { label: 'Distributed Systems', value: 'DISTRIBUTED_SYSTEMS' },
      { label: 'Frontend', value: 'FRONTEND' },
      { label: 'Fullstack', value: 'FULLSTACK' },
      { label: 'Mobile Android', value: 'MOBILE_ANDROID' },
      { label: 'Mobile iOS', value: 'MOBILE_IOS' },
      { label: 'Quality Assurance', value: 'QA' },
      { label: 'Other', value: 'OTHER' },
    ],
  },
  {
    title: 'AI, Data & ML',
    areas: [
      { label: 'Data Engineering', value: 'DATA_ENGINEERING' },
      { label: 'Data Science', value: 'DATA_SCIENCE' },
      { label: 'Machine Learning', value: 'MACHINE_LEARNING' },
    ],
  },
  {
    title: 'Infrastructure & Operations',
    areas: [
      { label: 'Cloud Engineer', value: 'CLOUD_ENGINEER' },
      { label: 'DevOps', value: 'DEVOPS' },
      { label: 'Network Engineering', value: 'NETWORK_ENGINEERING' },
      { label: 'Security', value: 'SECURITY' },
      { label: 'Site Reliability Engineering', value: 'SRE' },
    ],
  },
  {
    title: 'Product, Leadership & Delivery',
    areas: [
      { label: 'Business Analysis', value: 'BUSINESS_ANALYSIS' },
      { label: 'Engineering Management', value: 'ENG_MANAGEMENT' },
      { label: 'Product Management', value: 'PROD_MANAGEMENT' },
      { label: 'Project Management', value: 'PROJ_MANAGEMENT' },
    ],
  },
];

export const TECHNICAL_AREAS: LabelValue[] = TECHNICAL_AREA_GROUPS.flatMap(
  (g) => g.areas,
);

export const CODE_LANGUAGES: LabelValue[] = [
  { label: 'Bash', value: 'BASH' },
  { label: 'C', value: 'C_LANGUAGE' },
  { label: 'C++', value: 'C_PLUS_PLUS' },
  { label: 'C#', value: 'C_SHARP' },
  { label: 'Dart', value: 'DART' },
  { label: 'Go', value: 'GO' },
  { label: 'HCL', value: 'HCL' },
  { label: 'Java', value: 'JAVA' },
  { label: 'JavaScript', value: 'JAVASCRIPT' },
  { label: 'Kotlin', value: 'KOTLIN' },
  { label: 'OpenTofu', value: 'OPENTOFU' },
  { label: 'PHP', value: 'PHP' },
  { label: 'Python', value: 'PYTHON' },
  { label: 'Rego', value: 'REGO' },
  { label: 'Ruby', value: 'RUBY' },
  { label: 'Rust', value: 'RUST' },
  { label: 'Scala', value: 'SCALA' },
  { label: 'Swift', value: 'SWIFT' },
  { label: 'Terraform', value: 'TERRAFORM' },
  { label: 'TypeScript', value: 'TYPESCRIPT' },
  { label: 'Yaml', value: 'YAML' },
  { label: 'Other', value: 'OTHER' },
];

export const SPOKEN_LANGUAGES: LabelValue[] = [
  { label: 'English', value: 'English' },
  { label: 'French', value: 'French' },
  { label: 'German', value: 'German' },
  { label: 'Spanish', value: 'Spanish' },
  { label: 'Italian', value: 'Italian' },
  { label: 'Dutch', value: 'Dutch' },
  { label: 'Hindi', value: 'Hindi' },
  { label: 'Polish', value: 'Polish' },
  { label: 'Portuguese', value: 'Portuguese' },
  { label: 'Russian', value: 'Russian' },
  { label: 'Ukrainian', value: 'Ukrainian' },
  { label: 'Other', value: 'Other' },
];

export const MENTOR_EXPERIENCE_LEVELS: string[] = [
  '0–2 years',
  '3–5 years',
  '6–10 years',
  '10+ years',
];

export const MENTEE_EXPERIENCE_OPTIONS = [
  { label: 'No experience', value: 0 },
  { label: '0–1 year', value: 1 },
  { label: '1–2 years', value: 2 },
  { label: '3–5 years', value: 3 },
  { label: '6–9 years', value: 6 },
  { label: '10+ years', value: 10 },
];

export const FILTER_EXPERIENCE_OPTIONS = [
  { label: 'Any', value: '0' },
  { label: '3+ years', value: '3' },
  { label: '5+ years', value: '5' },
  { label: '10+ years', value: '10' },
];

const createCountries = (data: Array<[string, string]>): Country[] =>
  data.map(([code, name]) => ({ code, name }));

export const COUNTRIES = createCountries([
  ['AF', 'Afghanistan'],
  ['AL', 'Albania'],
  ['DZ', 'Algeria'],
  ['AS', 'American Samoa'],
  ['AD', 'Andorra'],
  ['AO', 'Angola'],
  ['AI', 'Anguilla'],
  ['AQ', 'Antarctica'],
  ['AG', 'Antigua and Barbuda'],
  ['AR', 'Argentina'],
  ['AM', 'Armenia'],
  ['AW', 'Aruba'],
  ['AU', 'Australia'],
  ['AT', 'Austria'],
  ['AZ', 'Azerbaijan'],
  ['BS', 'Bahamas'],
  ['BH', 'Bahrain'],
  ['BD', 'Bangladesh'],
  ['BB', 'Barbados'],
  ['BY', 'Belarus'],
  ['BE', 'Belgium'],
  ['BZ', 'Belize'],
  ['BJ', 'Benin'],
  ['BM', 'Bermuda'],
  ['BT', 'Bhutan'],
  ['BO', 'Bolivia, Plurinational State of'],
  ['BQ', 'Bonaire, Sint Eustatius and Saba'],
  ['BA', 'Bosnia and Herzegovina'],
  ['BW', 'Botswana'],
  ['BV', 'Bouvet Island'],
  ['BR', 'Brazil'],
  ['IO', 'British Indian Ocean Territory'],
  ['BN', 'Brunei Darussalam'],
  ['BG', 'Bulgaria'],
  ['BF', 'Burkina Faso'],
  ['BI', 'Burundi'],
  ['KH', 'Cambodia'],
  ['CM', 'Cameroon'],
  ['CA', 'Canada'],
  ['CV', 'Cape Verde'],
  ['KY', 'Cayman Islands'],
  ['CF', 'Central African Republic'],
  ['TD', 'Chad'],
  ['CL', 'Chile'],
  ['CN', 'China'],
  ['CX', 'Christmas Island'],
  ['CC', 'Cocos (Keeling) Islands'],
  ['CO', 'Colombia'],
  ['KM', 'Comoros'],
  ['CG', 'Congo'],
  ['CD', 'Congo, the Democratic Republic of the'],
  ['CK', 'Cook Islands'],
  ['CR', 'Costa Rica'],
  ['HR', 'Croatia'],
  ['CU', 'Cuba'],
  ['CW', 'Curaçao'],
  ['CY', 'Cyprus'],
  ['CZ', 'Czech Republic'],
  ['CI', "Côte d'Ivoire"],
  ['DK', 'Denmark'],
  ['DJ', 'Djibouti'],
  ['DM', 'Dominica'],
  ['DO', 'Dominican Republic'],
  ['EC', 'Ecuador'],
  ['EG', 'Egypt'],
  ['SV', 'El Salvador'],
  ['GQ', 'Equatorial Guinea'],
  ['ER', 'Eritrea'],
  ['EE', 'Estonia'],
  ['SZ', 'Eswatini'],
  ['ET', 'Ethiopia'],
  ['FK', 'Falkland Islands (Malvinas)'],
  ['FO', 'Faroe Islands'],
  ['FJ', 'Fiji'],
  ['FI', 'Finland'],
  ['FR', 'France'],
  ['GF', 'French Guiana'],
  ['PF', 'French Polynesia'],
  ['TF', 'French Southern Territories'],
  ['GA', 'Gabon'],
  ['GM', 'Gambia'],
  ['GE', 'Georgia'],
  ['DE', 'Germany'],
  ['GH', 'Ghana'],
  ['GI', 'Gibraltar'],
  ['GR', 'Greece'],
  ['GL', 'Greenland'],
  ['GD', 'Grenada'],
  ['GP', 'Guadeloupe'],
  ['GU', 'Guam'],
  ['GT', 'Guatemala'],
  ['GG', 'Guernsey'],
  ['GN', 'Guinea'],
  ['GW', 'Guinea-Bissau'],
  ['GY', 'Guyana'],
  ['HT', 'Haiti'],
  ['HM', 'Heard Island and McDonald Islands'],
  ['VA', 'Holy See (Vatican City State)'],
  ['HN', 'Honduras'],
  ['HK', 'Hong Kong'],
  ['HU', 'Hungary'],
  ['IS', 'Iceland'],
  ['IN', 'India'],
  ['ID', 'Indonesia'],
  ['IR', 'Iran, Islamic Republic of'],
  ['IQ', 'Iraq'],
  ['IE', 'Ireland'],
  ['IM', 'Isle of Man'],
  ['IL', 'Israel'],
  ['IT', 'Italy'],
  ['JM', 'Jamaica'],
  ['JP', 'Japan'],
  ['JE', 'Jersey'],
  ['JO', 'Jordan'],
  ['KZ', 'Kazakhstan'],
  ['KE', 'Kenya'],
  ['KI', 'Kiribati'],
  ['KP', "Korea, Democratic People's Republic of"],
  ['KR', 'Korea, Republic of'],
  ['KW', 'Kuwait'],
  ['KG', 'Kyrgyzstan'],
  ['LA', "Lao People's Democratic Republic"],
  ['LV', 'Latvia'],
  ['LB', 'Lebanon'],
  ['LS', 'Lesotho'],
  ['LR', 'Liberia'],
  ['LY', 'Libya'],
  ['LI', 'Liechtenstein'],
  ['LT', 'Lithuania'],
  ['LU', 'Luxembourg'],
  ['MO', 'Macao'],
  ['MK', 'Macedonia, the Former Yugoslav Republic of'],
  ['MG', 'Madagascar'],
  ['MW', 'Malawi'],
  ['MY', 'Malaysia'],
  ['MV', 'Maldives'],
  ['ML', 'Mali'],
  ['MT', 'Malta'],
  ['MH', 'Marshall Islands'],
  ['MQ', 'Martinique'],
  ['MR', 'Mauritania'],
  ['MU', 'Mauritius'],
  ['YT', 'Mayotte'],
  ['MX', 'Mexico'],
  ['FM', 'Micronesia, Federated States of'],
  ['MD', 'Moldova, Republic of'],
  ['MC', 'Monaco'],
  ['MN', 'Mongolia'],
  ['ME', 'Montenegro'],
  ['MS', 'Montserrat'],
  ['MA', 'Morocco'],
  ['MZ', 'Mozambique'],
  ['MM', 'Myanmar'],
  ['NA', 'Namibia'],
  ['NR', 'Nauru'],
  ['NP', 'Nepal'],
  ['NL', 'Netherlands'],
  ['NC', 'New Caledonia'],
  ['NZ', 'New Zealand'],
  ['NI', 'Nicaragua'],
  ['NE', 'Niger'],
  ['NG', 'Nigeria'],
  ['NU', 'Niue'],
  ['NF', 'Norfolk Island'],
  ['MP', 'Northern Mariana Islands'],
  ['NO', 'Norway'],
  ['OM', 'Oman'],
  ['PK', 'Pakistan'],
  ['PW', 'Palau'],
  ['PS', 'Palestine, State of'],
  ['PA', 'Panama'],
  ['PG', 'Papua New Guinea'],
  ['PY', 'Paraguay'],
  ['PE', 'Peru'],
  ['PH', 'Philippines'],
  ['PN', 'Pitcairn'],
  ['PL', 'Poland'],
  ['PT', 'Portugal'],
  ['PR', 'Puerto Rico'],
  ['QA', 'Qatar'],
  ['RO', 'Romania'],
  ['RU', 'Russian Federation'],
  ['RW', 'Rwanda'],
  ['RE', 'Réunion'],
  ['BL', 'Saint Barthélemy'],
  ['SH', 'Saint Helena, Ascension and Tristan da Cunha'],
  ['KN', 'Saint Kitts and Nevis'],
  ['LC', 'Saint Lucia'],
  ['MF', 'Saint Martin (French part)'],
  ['PM', 'Saint Pierre and Miquelon'],
  ['VC', 'Saint Vincent and the Grenadines'],
  ['WS', 'Samoa'],
  ['SM', 'San Marino'],
  ['ST', 'Sao Tome and Principe'],
  ['SA', 'Saudi Arabia'],
  ['SN', 'Senegal'],
  ['RS', 'Serbia'],
  ['SC', 'Seychelles'],
  ['SL', 'Sierra Leone'],
  ['SG', 'Singapore'],
  ['SX', 'Sint Maarten (Dutch part)'],
  ['SK', 'Slovakia'],
  ['SI', 'Slovenia'],
  ['SB', 'Solomon Islands'],
  ['SO', 'Somalia'],
  ['ZA', 'South Africa'],
  ['GS', 'South Georgia and the South Sandwich Islands'],
  ['SS', 'South Sudan'],
  ['ES', 'Spain'],
  ['LK', 'Sri Lanka'],
  ['SD', 'Sudan'],
  ['SR', 'Suriname'],
  ['SJ', 'Svalbard and Jan Mayen'],
  ['SE', 'Sweden'],
  ['CH', 'Switzerland'],
  ['SY', 'Syrian Arab Republic'],
  ['TW', 'Taiwan, Province of China'],
  ['TJ', 'Tajikistan'],
  ['TZ', 'Tanzania, United Republic of'],
  ['TH', 'Thailand'],
  ['TL', 'Timor-Leste'],
  ['TG', 'Togo'],
  ['TK', 'Tokelau'],
  ['TO', 'Tonga'],
  ['TT', 'Trinidad and Tobago'],
  ['TN', 'Tunisia'],
  ['TR', 'Turkey'],
  ['TM', 'Turkmenistan'],
  ['TC', 'Turks and Caicos Islands'],
  ['TV', 'Tuvalu'],
  ['UG', 'Uganda'],
  ['UA', 'Ukraine'],
  ['AE', 'United Arab Emirates'],
  ['GB', 'United Kingdom'],
  ['US', 'United States'],
  ['UM', 'United States Minor Outlying Islands'],
  ['UY', 'Uruguay'],
  ['UZ', 'Uzbekistan'],
  ['VU', 'Vanuatu'],
  ['VE', 'Venezuela, Bolivarian Republic of'],
  ['VN', 'Viet Nam'],
  ['VG', 'Virgin Islands, British'],
  ['VI', 'Virgin Islands, U.S.'],
  ['WF', 'Wallis and Futuna'],
  ['EH', 'Western Sahara'],
  ['YE', 'Yemen'],
  ['ZM', 'Zambia'],
  ['ZW', 'Zimbabwe'],
  ['AX', 'Åland Islands'],
  ['OTHER', 'Other'],
]);

// Legacy — kept for backward compatibility with mentor form Step 3/4 until migrated
export const SKILL_LEVELS = [
  'Expert',
  'Proficient',
  'Experienced',
  'Familiar',
  'Not Applicable',
];
export const PREFERENCE_LEVELS = ['Low', 'Medium', 'High', 'Not Applicable'];
